services:
  backend:
    build:
      context: ./backend
    image: spa-project-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
  frontend:
    build:
      context: ./frontend
    image: spa-project-frontend
    ports:
      - "3001:80"
    enviroment:
      - REACT_APP_API_BASE=http://backend:3000
    depends_on:
      - backend
